AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: F1 Data Project - Equipo 10

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: F1ProjectRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  F1Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: f1-api
      StageName: prod

  DriversFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: f1-list-drivers
      Handler: handler.handler
      CodeUri: ./lambda-functions/drivers
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetDrivers:
          Type: Api
          Properties:
            RestApiId: !Ref F1Api
            Path: /drivers
            Method: GET

  GetSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: f1-get-session
      Handler: handler.handler
      CodeUri: ./lambda-functions/get-session
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetSession:
          Type: Api
          Properties:
            RestApiId: !Ref F1Api
            Path: /session
            Method: GET

Outputs:
  ApiUrl:
    Description: URL base del API Gateway
    Value: !Sub "https://${F1Api}.execute-api.${AWS::Region}.amazonaws.com/prod"